services:
  web-reverse-proxy:
    image: nginx:latest
    container_name: web-reverse-proxy
    ports:
      - "8555:8555"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend_net
      - public_net

networks:
  public_net:
    external: true
  frontend_net:
    external: true
